"use client";

import React, { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { fetchAdminDashboard, AdminDashboardStats } from "@/lib/api";

export default function AdminDashboardPage() {
  const router = useRouter();
  const [stats, setStats] = useState<AdminDashboardStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const loadDashboard = async () => {
    try {
      setLoading(true);
      setError(null);
      const data = await fetchAdminDashboard();
      setStats(data);
    } catch (err: any) {
      setError(err.message || "Failed to load dashboard statistics.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadDashboard();
  }, []);

  if (loading) {
    return (
      <div style={{ display: "flex", justifyContent: "center", alignItems: "center", minHeight: "50vh", color: "#64748B" }}>
        <div style={{ textAlign: "center" }}>
          <div style={{ fontSize: "28px", marginBottom: "10px" }}>⏳</div>
          <p style={{ fontSize: "14px", fontWeight: 500, color: "#64748B" }}>Loading platform analytics...</p>
        </div>
      </div>
    );
  }

  if (error || !stats) {
    return (
      <div style={{ backgroundColor: "#FEF2F2", border: "1px solid #FCA5A5", borderRadius: "12px", padding: "24px", color: "#991B1B" }}>
        <h3 style={{ margin: "0 0 8px 0", fontSize: "16px", fontWeight: 700 }}>Error Loading Dashboard</h3>
        <p style={{ margin: "0 0 16px 0", fontSize: "13.5px" }}>{error || "Unknown error occurred"}</p>
        <button
          onClick={loadDashboard}
          style={{
            backgroundColor: "#DC2626", color: "#FFFFFF", border: "none", padding: "8px 16px",
            borderRadius: "6px", fontWeight: 600, cursor: "pointer", fontSize: "13px"
          }}
        >
          Retry
        </button>
      </div>
    );
  }

  const statCards = [
    {
      title: "Total Candidates",
      value: stats.total_users,
      subtext: `${stats.active_users} active · ${stats.suspended_users} suspended`,
      icon: "👥",
      color: "#2563EB",
      iconBg: "#EFF6FF",
      href: "/admin/users"
    },
    {
      title: "Active Features",
      value: stats.total_features,
      subtext: `${stats.feature_usage.length} modules configured`,
      icon: "⚡",
      color: "#7C3AED",
      iconBg: "#F5F3FF",
      href: "/admin/features"
    },
    {
      title: "Resumes Built",
      value: stats.total_resumes,
      subtext: "Generated by candidates",
      icon: "📄",
      color: "#16A34A",
      iconBg: "#F0FDF4",
      href: "/admin/users"
    },
    {
      title: "Interview Prep Sessions",
      value: stats.total_interview_sessions,
      subtext: `${stats.total_interview_feedbacks} feedback responses`,
      icon: "💬",
      color: "#D97706",
      iconBg: "#FFFBEB",
      href: "/admin/users"
    },
  ];

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "28px" }}>
      {/* Top Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end", flexWrap: "wrap", gap: "16px" }}>
        <div>
          <h1 style={{ fontSize: "26px", fontWeight: 800, margin: "0 0 6px 0", color: "#0F172A", letterSpacing: "-0.02em" }}>
            Admin Overview
          </h1>
          <p style={{ fontSize: "14.5px", color: "#64748B", margin: 0 }}>
            Platform metrics, feature distribution, and access management.
          </p>
        </div>

        <div style={{ display: "flex", gap: "12px" }}>
          <button
            onClick={() => router.push("/admin/users")}
            style={{
              backgroundColor: "#2563EB",
              color: "#FFFFFF",
              border: "none",
              borderRadius: "8px",
              padding: "10px 18px",
              fontSize: "13px",
              fontWeight: 600,
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              gap: "6px",
              boxShadow: "0 1px 3px rgba(37, 99, 235, 0.25)",
              transition: "background-color 0.15s ease",
            }}
            onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = "#1D4ED8"; }}
            onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = "#2563EB"; }}
          >
            👥 Manage Users
          </button>
          <button
            onClick={() => router.push("/admin/features")}
            style={{
              backgroundColor: "#FFFFFF",
              color: "#0F172A",
              border: "1px solid #CBD5E1",
              borderRadius: "8px",
              padding: "10px 18px",
              fontSize: "13px",
              fontWeight: 600,
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              gap: "6px",
              boxShadow: "0 1px 2px rgba(0,0,0,0.03)",
              transition: "background-color 0.15s ease",
            }}
            onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = "#F8FAFC"; }}
            onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = "#FFFFFF"; }}
          >
            ⚡ Feature Controls
          </button>
        </div>
      </div>

      {/* 4 Stat Cards in Row */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: "20px" }}>
        {statCards.map((card, idx) => (
          <div
            key={idx}
            onClick={() => router.push(card.href)}
            style={{
              backgroundColor: "#FFFFFF",
              border: "1px solid #E2E8F0",
              borderRadius: "14px",
              padding: "22px 24px",
              cursor: "pointer",
              boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
              transition: "transform 0.15s ease, box-shadow 0.15s ease, border-color 0.15s ease",
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.transform = "translateY(-2px)";
              e.currentTarget.style.boxShadow = "0 10px 20px -5px rgba(0,0,0,0.08)";
              e.currentTarget.style.borderColor = card.color;
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.transform = "translateY(0)";
              e.currentTarget.style.boxShadow = "0 1px 3px rgba(0,0,0,0.04)";
              e.currentTarget.style.borderColor = "#E2E8F0";
            }}
          >
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "12px" }}>
              <span style={{ fontSize: "13.5px", fontWeight: 600, color: "#64748B" }}>{card.title}</span>
              <div style={{
                width: "36px", height: "36px", borderRadius: "8px",
                backgroundColor: card.iconBg, display: "flex", alignItems: "center",
                justifyContent: "center", fontSize: "18px"
              }}>
                {card.icon}
              </div>
            </div>
            <div style={{ fontSize: "32px", fontWeight: 800, color: "#0F172A", marginBottom: "4px", letterSpacing: "-0.02em" }}>
              {card.value}
            </div>
            <div style={{ fontSize: "12px", color: "#64748B", fontWeight: 500 }}>
              {card.subtext}
            </div>
          </div>
        ))}
      </div>

      {/* 2 Column Layout */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "24px" }}>
        
        {/* Feature Usage Overview Card */}
        <div style={{
          backgroundColor: "#FFFFFF",
          border: "1px solid #E2E8F0",
          borderRadius: "14px",
          padding: "24px",
          boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
        }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
            <div>
              <h2 style={{ fontSize: "17px", fontWeight: 700, margin: "0 0 2px 0", color: "#0F172A" }}>
                Feature Assignments
              </h2>
              <p style={{ fontSize: "12.5px", color: "#64748B", margin: 0 }}>
                Active candidates entitled per platform feature
              </p>
            </div>
            <button
              onClick={() => router.push("/admin/features")}
              style={{
                background: "none", border: "none", color: "#2563EB", fontSize: "12.5px",
                fontWeight: 600, cursor: "pointer", padding: "4px 8px", borderRadius: "4px"
              }}
            >
              Configure →
            </button>
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
            {stats.feature_usage.length === 0 ? (
              <div style={{ color: "#94A3B8", fontSize: "13px", textAlign: "center", padding: "20px 0" }}>
                No features registered yet.
              </div>
            ) : (
              stats.feature_usage.map((feat) => {
                const percentage = stats.total_users > 0 ? Math.round((feat.enabled_users_count / stats.total_users) * 100) : 0;
                return (
                  <div key={feat.feature_id}>
                    <div style={{ display: "flex", justifyContent: "space-between", fontSize: "13px", marginBottom: "6px" }}>
                      <span style={{ fontWeight: 600, color: "#334155" }}>{feat.feature_name}</span>
                      <span style={{ color: "#64748B", fontSize: "12px", fontWeight: 600 }}>
                        {feat.enabled_users_count} / {stats.total_users} users ({percentage}%)
                      </span>
                    </div>
                    <div style={{
                      height: "8px", backgroundColor: "#F1F5F9", borderRadius: "4px", overflow: "hidden"
                    }}>
                      <div style={{
                        height: "100%", width: `${percentage}%`,
                        background: "linear-gradient(90deg, #2563EB 0%, #7C3AED 100%)",
                        borderRadius: "4px", transition: "width 0.4s ease"
                      }} />
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* Recent Users Card */}
        <div style={{
          backgroundColor: "#FFFFFF",
          border: "1px solid #E2E8F0",
          borderRadius: "14px",
          padding: "24px",
          boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
        }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
            <div>
              <h2 style={{ fontSize: "17px", fontWeight: 700, margin: "0 0 2px 0", color: "#0F172A" }}>
                Recent Users
              </h2>
              <p style={{ fontSize: "12.5px", color: "#64748B", margin: 0 }}>
                Latest candidates registered on the platform
              </p>
            </div>
            <button
              onClick={() => router.push("/admin/users")}
              style={{
                background: "none", border: "none", color: "#2563EB", fontSize: "12.5px",
                fontWeight: 600, cursor: "pointer", padding: "4px 8px", borderRadius: "4px"
              }}
            >
              View All ({stats.total_users}) →
            </button>
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
            {stats.recent_users.length === 0 ? (
              <div style={{ color: "#94A3B8", fontSize: "13px", textAlign: "center", padding: "20px 0" }}>
                No candidates registered yet.
              </div>
            ) : (
              stats.recent_users.slice(0, 6).map((u) => (
                <div
                  key={u.id}
                  onClick={() => router.push(`/admin/users/${u.id}`)}
                  style={{
                    display: "flex", alignItems: "center", justifyContent: "space-between",
                    padding: "10px 14px", borderRadius: "8px", backgroundColor: "#FFFFFF",
                    border: "1px solid #E2E8F0", cursor: "pointer",
                    boxShadow: "0 1px 2px rgba(0,0,0,0.02)",
                    transition: "all 0.15s ease"
                  }}
                  onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = "#F8FAFC"; e.currentTarget.style.borderColor = "#CBD5E1"; }}
                  onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = "#FFFFFF"; e.currentTarget.style.borderColor = "#E2E8F0"; }}
                >
                  <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                    <div style={{
                      width: "32px", height: "32px", borderRadius: "50%",
                      backgroundColor: u.role === "admin" ? "#F59E0B" : "#2563EB",
                      color: "#FFFFFF", display: "flex", alignItems: "center", justifyContent: "center",
                      fontWeight: 700, fontSize: "12px"
                    }}>
                      {u.full_name ? u.full_name[0].toUpperCase() : "U"}
                    </div>
                    <div>
                      <div style={{ fontSize: "13px", fontWeight: 600, color: "#0F172A" }}>{u.full_name}</div>
                      <div style={{ fontSize: "11px", color: "#64748B" }}>{u.email}</div>
                    </div>
                  </div>

                  <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                    <span style={{
                      fontSize: "10.5px", fontWeight: 700, padding: "2px 8px", borderRadius: "10px",
                      backgroundColor: u.role === "admin" ? "#FEF3C7" : "#EFF6FF",
                      color: u.role === "admin" ? "#D97706" : "#2563EB",
                    }}>
                      {u.role.toUpperCase()}
                    </span>
                    <span style={{
                      fontSize: "10.5px", fontWeight: 700, padding: "2px 8px", borderRadius: "10px",
                      backgroundColor: u.is_active ? "#DCFCE7" : "#FEE2E2",
                      color: u.is_active ? "#15803D" : "#DC2626",
                    }}>
                      {u.is_active ? "Active" : "Suspended"}
                    </span>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
