"use client";

import React, { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { fetchAdminDashboard, AdminDashboardStats, AIUsageStats, AIUsageLogEntry } from "@/lib/api";
import {
  Users,
  Sliders,
  FileText,
  MessageSquare,
  Loader2,
  Cpu,
  Zap,
  Activity,
  Key,
  Clock,
  CheckCircle2,
  AlertTriangle,
  RefreshCw,
  BarChart2,
  Terminal,
  ToggleLeft,
  ArrowRight,
  TrendingUp,
} from "lucide-react";

export default function AdminDashboardPage() {
  const router = useRouter();
  const [stats, setStats] = useState<AdminDashboardStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<"overview" | "ai_analytics">("overview");
  const [logFilter, setLogFilter] = useState<string>("all");

  const loadDashboard = async (isManualRefresh = false) => {
    try {
      if (isManualRefresh) setRefreshing(true);
      else setLoading(true);
      setError(null);
      const data = await fetchAdminDashboard();
      setStats(data);
    } catch (err: any) {
      setError(err.message || "Failed to load dashboard statistics.");
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    loadDashboard();
    
    // Auto-refresh dashboard every 10 seconds when viewing AI analytics
    const refreshInterval = setInterval(() => {
      if (activeTab === "ai_analytics") {
        loadDashboard();
      }
    }, 10000);
    
    return () => clearInterval(refreshInterval);
  }, [activeTab]);

  if (loading) {
    return (
      <div style={{ display: "flex", justifyContent: "center", alignItems: "center", minHeight: "50vh", color: "#64748B" }}>
        <div style={{ textAlign: "center" }}>
          <Loader2 size={32} color="#2563EB" style={{ animation: "spin 1s linear infinite", margin: "0 auto 10px auto" }} />
          <p style={{ fontSize: "14px", fontWeight: 500, color: "#64748B" }}>Loading platform & AI analytics...</p>
        </div>
      </div>
    );
  }

  if (error || !stats) {
    return (
      <div style={{ backgroundColor: "#FEF2F2", border: "1px solid #FCA5A5", borderRadius: "12px", padding: "24px", color: "#991B1B" }}>
        <h3 style={{ margin: "0 0 8px 0", fontSize: "16px", fontWeight: 700 }}>Error Loading Dashboard</h3>
        <p style={{ margin: "0 0 16px 0", fontSize: "13.5px" }}>{error || "Unknown error occurred"}</p>
        <button
          onClick={() => loadDashboard()}
          style={{
            backgroundColor: "#DC2626", color: "#FFFFFF", border: "none", padding: "8px 16px",
            borderRadius: "6px", fontWeight: 600, cursor: "pointer", fontSize: "13px"
          }}
        >
          Retry
        </button>
      </div>
    );
  }

  const aiStats: AIUsageStats = stats.ai_usage || {
    total_calls: 0,
    total_input_tokens: 0,
    total_output_tokens: 0,
    total_tokens: 0,
    avg_response_time_ms: 0,
    active_keys_count: 0,
    total_keys_count: 0,
    feature_breakdown: [],
    top_users: [],
    model_breakdown: [],
    recent_logs: [],
  };

  const statCards = [
    {
      title: "Total Candidates",
      value: stats.total_users,
      subtext: `${stats.active_users} active · ${stats.suspended_users} suspended`,
      icon: Users,
      color: "#2563EB",
      iconBg: "#EFF6FF",
      href: "/admin/users"
    },
    {
      title: "Active Features",
      value: stats.total_features,
      subtext: `${stats.feature_usage.length} modules configured`,
      icon: Sliders,
      color: "#7C3AED",
      iconBg: "#F5F3FF",
      href: "/admin/features"
    },
    {
      title: "Resumes Built",
      value: stats.total_resumes,
      subtext: "Generated by candidates",
      icon: FileText,
      color: "#16A34A",
      iconBg: "#F0FDF4",
      href: "/admin/users"
    },
    {
      title: "AI Calls Executed",
      value: aiStats.total_calls.toLocaleString(),
      subtext: `${aiStats.total_tokens.toLocaleString()} tokens tracked`,
      icon: Cpu,
      color: "#D97706",
      iconBg: "#FFFBEB",
      onClick: () => setActiveTab("ai_analytics")
    },
  ];

  const filteredLogs = aiStats.recent_logs.filter((log) => {
    if (logFilter === "all") return true;
    if (logFilter === "errors") return log.status !== "success";
    return log.feature.toLowerCase().includes(logFilter.toLowerCase());
  });

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "28px" }}>
      {/* Top Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end", flexWrap: "wrap", gap: "16px" }}>
        <div>
          <h1 style={{ fontSize: "26px", fontWeight: 800, margin: "0 0 6px 0", color: "#0F172A", letterSpacing: "-0.02em" }}>
            Admin Control Center
          </h1>
          <p style={{ fontSize: "14.5px", color: "#64748B", margin: 0 }}>
            Platform metrics, AI model token usage, feature distribution, and access management.
          </p>
        </div>

        <div style={{ display: "flex", gap: "10px", alignItems: "center" }}>
          <button
            onClick={() => loadDashboard(true)}
            disabled={refreshing}
            style={{
              backgroundColor: "#FFFFFF",
              color: "#334155",
              border: "1px solid #CBD5E1",
              borderRadius: "8px",
              padding: "9px 14px",
              fontSize: "13px",
              fontWeight: 600,
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              gap: "6px",
              boxShadow: "0 1px 2px rgba(0,0,0,0.03)",
            }}
          >
            <RefreshCw size={14} style={{ animation: refreshing ? "spin 1s linear infinite" : "none" }} />
            <span>{refreshing ? "Refreshing..." : "Refresh"}</span>
          </button>
          <button
            onClick={() => router.push("/admin/users")}
            style={{
              backgroundColor: "#2563EB",
              color: "#FFFFFF",
              border: "none",
              borderRadius: "8px",
              padding: "10px 16px",
              fontSize: "13px",
              fontWeight: 600,
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              gap: "8px",
              boxShadow: "0 1px 3px rgba(37, 99, 235, 0.25)",
            }}
          >
            <Users size={16} />
            <span>Users</span>
          </button>
          <button
            onClick={() => router.push("/admin/features")}
            style={{
              backgroundColor: "#FFFFFF",
              color: "#0F172A",
              border: "1px solid #CBD5E1",
              borderRadius: "8px",
              padding: "10px 16px",
              fontSize: "13px",
              fontWeight: 600,
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              gap: "8px",
            }}
          >
            <ToggleLeft size={16} color="#7C3AED" />
            <span>Features</span>
          </button>
        </div>
      </div>

      {/* Navigation Tabs */}
      <div style={{ display: "flex", gap: "8px", borderBottom: "1px solid #E2E8F0", paddingBottom: "2px" }}>
        <button
          onClick={() => setActiveTab("overview")}
          style={{
            padding: "8px 16px",
            fontSize: "14px",
            fontWeight: activeTab === "overview" ? 700 : 500,
            color: activeTab === "overview" ? "#2563EB" : "#64748B",
            border: "none",
            background: "none",
            borderBottom: activeTab === "overview" ? "2px solid #2563EB" : "2px solid transparent",
            cursor: "pointer",
            display: "flex",
            alignItems: "center",
            gap: "8px",
            marginBottom: "-2px",
          }}
        >
          <BarChart2 size={16} />
          <span>Platform Overview</span>
        </button>
        <button
          onClick={() => setActiveTab("ai_analytics")}
          style={{
            padding: "8px 16px",
            fontSize: "14px",
            fontWeight: activeTab === "ai_analytics" ? 700 : 500,
            color: activeTab === "ai_analytics" ? "#2563EB" : "#64748B",
            border: "none",
            background: "none",
            borderBottom: activeTab === "ai_analytics" ? "2px solid #2563EB" : "2px solid transparent",
            cursor: "pointer",
            display: "flex",
            alignItems: "center",
            gap: "8px",
            marginBottom: "-2px",
          }}
        >
          <Cpu size={16} color={activeTab === "ai_analytics" ? "#2563EB" : "#7C3AED"} />
          <span>AI Model & Token Analytics</span>
          <span style={{
            fontSize: "11px",
            fontWeight: 700,
            backgroundColor: "#EFF6FF",
            color: "#2563EB",
            padding: "2px 6px",
            borderRadius: "10px"
          }}>
            {aiStats.total_tokens.toLocaleString()} tokens
          </span>
        </button>
      </div>

      {/* 4 Stat Cards in Row */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "16px" }}>
        {statCards.map((card, idx) => {
          const CardIcon = card.icon;
          return (
            <div
              key={idx}
              onClick={() => {
                if (card.onClick) card.onClick();
                else if (card.href) router.push(card.href);
              }}
              style={{
                backgroundColor: "#FFFFFF",
                border: "1px solid #E2E8F0",
                borderRadius: "14px",
                padding: "20px",
                cursor: "pointer",
                boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
                transition: "transform 0.15s ease, box-shadow 0.15s ease, border-color 0.15s ease",
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.transform = "translateY(-2px)";
                e.currentTarget.style.boxShadow = "0 10px 20px -5px rgba(0,0,0,0.08)";
                e.currentTarget.style.borderColor = card.color;
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.transform = "translateY(0)";
                e.currentTarget.style.boxShadow = "0 1px 3px rgba(0,0,0,0.04)";
                e.currentTarget.style.borderColor = "#E2E8F0";
              }}
            >
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "12px" }}>
                <span style={{ fontSize: "13.5px", fontWeight: 600, color: "#64748B" }}>{card.title}</span>
                <div style={{
                  width: "36px", height: "36px", borderRadius: "8px",
                  backgroundColor: card.iconBg, display: "flex", alignItems: "center",
                  justifyContent: "center"
                }}>
                  <CardIcon size={18} color={card.color} />
                </div>
              </div>
              <div style={{ fontSize: "30px", fontWeight: 800, color: "#0F172A", marginBottom: "4px", letterSpacing: "-0.02em" }}>
                {card.value}
              </div>
              <div style={{ fontSize: "12px", color: "#64748B", fontWeight: 500 }}>
                {card.subtext}
              </div>
            </div>
          );
        })}
      </div>

      {/* ────────────────── TAB 1: OVERVIEW ────────────────── */}
      {activeTab === "overview" && (
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 340px), 1fr))", gap: "24px" }}>
          {/* Feature Usage Overview Card */}
          <div style={{
            backgroundColor: "#FFFFFF",
            border: "1px solid #E2E8F0",
            borderRadius: "14px",
            padding: "24px",
            boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
          }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
              <div>
                <h2 style={{ fontSize: "17px", fontWeight: 700, margin: "0 0 2px 0", color: "#0F172A" }}>
                  Feature Distribution
                </h2>
                <p style={{ fontSize: "12.5px", color: "#64748B", margin: 0 }}>
                  Active candidates entitled per platform module
                </p>
              </div>
              <button
                onClick={() => router.push("/admin/features")}
                style={{
                  background: "none", border: "none", color: "#2563EB", fontSize: "12.5px",
                  fontWeight: 600, cursor: "pointer", padding: "4px 8px", borderRadius: "4px"
                }}
              >
                Configure →
              </button>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
              {stats.feature_usage.length === 0 ? (
                <div style={{ color: "#94A3B8", fontSize: "13px", textAlign: "center", padding: "20px 0" }}>
                  No features registered yet.
                </div>
              ) : (
                stats.feature_usage.map((feat) => {
                  const percentage = stats.total_users > 0 ? Math.round((feat.enabled_users_count / stats.total_users) * 100) : 0;
                  return (
                    <div key={feat.feature_id}>
                      <div style={{ display: "flex", justifyContent: "space-between", fontSize: "13px", marginBottom: "6px" }}>
                        <span style={{ fontWeight: 600, color: "#334155" }}>{feat.feature_name}</span>
                        <span style={{ color: "#64748B", fontSize: "12px", fontWeight: 600 }}>
                          {feat.enabled_users_count} / {stats.total_users} users ({percentage}%)
                        </span>
                      </div>
                      <div style={{
                        height: "8px", backgroundColor: "#F1F5F9", borderRadius: "4px", overflow: "hidden"
                      }}>
                        <div style={{
                          height: "100%", width: `${percentage}%`,
                          background: "linear-gradient(90deg, #2563EB 0%, #7C3AED 100%)",
                          borderRadius: "4px", transition: "width 0.4s ease"
                        }} />
                      </div>
                    </div>
                  );
                })
              )}
            </div>
          </div>

          {/* Recent Users Card */}
          <div style={{
            backgroundColor: "#FFFFFF",
            border: "1px solid #E2E8F0",
            borderRadius: "14px",
            padding: "24px",
            boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
          }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
              <div>
                <h2 style={{ fontSize: "17px", fontWeight: 700, margin: "0 0 2px 0", color: "#0F172A" }}>
                  Recent Candidates
                </h2>
                <p style={{ fontSize: "12.5px", color: "#64748B", margin: 0 }}>
                  Latest users registered on the platform
                </p>
              </div>
              <button
                onClick={() => router.push("/admin/users")}
                style={{
                  background: "none", border: "none", color: "#2563EB", fontSize: "12.5px",
                  fontWeight: 600, cursor: "pointer", padding: "4px 8px", borderRadius: "4px"
                }}
              >
                View All ({stats.total_users}) →
              </button>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
              {stats.recent_users.length === 0 ? (
                <div style={{ color: "#94A3B8", fontSize: "13px", textAlign: "center", padding: "20px 0" }}>
                  No candidates registered yet.
                </div>
              ) : (
                stats.recent_users.slice(0, 6).map((u) => (
                  <div
                    key={u.id}
                    onClick={() => router.push(`/admin/users/${u.id}`)}
                    style={{
                      display: "flex", alignItems: "center", justifyContent: "space-between",
                      padding: "10px 14px", borderRadius: "8px", backgroundColor: "#FFFFFF",
                      border: "1px solid #E2E8F0", cursor: "pointer",
                      boxShadow: "0 1px 2px rgba(0,0,0,0.02)",
                      transition: "all 0.15s ease"
                    }}
                    onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = "#F8FAFC"; e.currentTarget.style.borderColor = "#CBD5E1"; }}
                    onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = "#FFFFFF"; e.currentTarget.style.borderColor = "#E2E8F0"; }}
                  >
                    <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                      <div style={{
                        width: "32px", height: "32px", borderRadius: "50%",
                        backgroundColor: u.role === "admin" ? "#F59E0B" : "#2563EB",
                        color: "#FFFFFF", display: "flex", alignItems: "center", justifyContent: "center",
                        fontWeight: 700, fontSize: "12px"
                      }}>
                        {u.full_name ? u.full_name[0].toUpperCase() : "U"}
                      </div>
                      <div>
                        <div style={{ fontSize: "13px", fontWeight: 600, color: "#0F172A" }}>{u.full_name}</div>
                        <div style={{ fontSize: "11px", color: "#64748B" }}>{u.email}</div>
                      </div>
                    </div>

                    <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                      <span style={{
                        fontSize: "10.5px", fontWeight: 700, padding: "2px 8px", borderRadius: "10px",
                        backgroundColor: u.role === "admin" ? "#FEF3C7" : "#EFF6FF",
                        color: u.role === "admin" ? "#D97706" : "#2563EB",
                      }}>
                        {u.role.toUpperCase()}
                      </span>
                      <span style={{
                        fontSize: "10.5px", fontWeight: 700, padding: "2px 8px", borderRadius: "10px",
                        backgroundColor: u.is_active ? "#DCFCE7" : "#FEE2E2",
                        color: u.is_active ? "#15803D" : "#DC2626",
                      }}>
                        {u.is_active ? "Active" : "Suspended"}
                      </span>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      )}

      {/* ────────────────── TAB 2: AI MODEL & TOKEN ANALYTICS ────────────────── */}
      {activeTab === "ai_analytics" && (
        <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
          
          {/* AI Metrics Row */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "16px" }}>
            <div style={{
              backgroundColor: "#FFFFFF", border: "1px solid #E2E8F0", borderRadius: "12px", padding: "18px",
              boxShadow: "0 1px 3px rgba(0,0,0,0.03)"
            }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "8px" }}>
                <span style={{ fontSize: "12.5px", fontWeight: 600, color: "#64748B" }}>Total Tokens</span>
                <Zap size={16} color="#7C3AED" />
              </div>
              <div style={{ fontSize: "24px", fontWeight: 800, color: "#0F172A" }}>
                {aiStats.total_tokens.toLocaleString()}
              </div>
              <div style={{ fontSize: "11.5px", color: "#64748B", marginTop: "4px" }}>
                {aiStats.total_input_tokens.toLocaleString()} prompt · {aiStats.total_output_tokens.toLocaleString()} completion
              </div>
            </div>

            <div style={{
              backgroundColor: "#FFFFFF", border: "1px solid #E2E8F0", borderRadius: "12px", padding: "18px",
              boxShadow: "0 1px 3px rgba(0,0,0,0.03)"
            }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "8px" }}>
                <span style={{ fontSize: "12.5px", fontWeight: 600, color: "#64748B" }}>Total AI Invocations</span>
                <Cpu size={16} color="#2563EB" />
              </div>
              <div style={{ fontSize: "24px", fontWeight: 800, color: "#0F172A" }}>
                {aiStats.total_calls.toLocaleString()}
              </div>
              <div style={{ fontSize: "11.5px", color: "#16A34A", marginTop: "4px", display: "flex", alignItems: "center", gap: "4px" }}>
                <CheckCircle2 size={12} />
                <span>100% failover resilience</span>
              </div>
            </div>

            <div style={{
              backgroundColor: "#FFFFFF", border: "1px solid #E2E8F0", borderRadius: "12px", padding: "18px",
              boxShadow: "0 1px 3px rgba(0,0,0,0.03)"
            }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "8px" }}>
                <span style={{ fontSize: "12.5px", fontWeight: 600, color: "#64748B" }}>Avg Latency</span>
                <Clock size={16} color="#D97706" />
              </div>
              <div style={{ fontSize: "24px", fontWeight: 800, color: "#0F172A" }}>
                {aiStats.avg_response_time_ms > 0 ? `${aiStats.avg_response_time_ms} ms` : "N/A"}
              </div>
              <div style={{ fontSize: "11.5px", color: "#64748B", marginTop: "4px" }}>
                Hugging Face Router API
              </div>
            </div>

            <div style={{
              backgroundColor: "#FFFFFF", border: "1px solid #E2E8F0", borderRadius: "12px", padding: "18px",
              boxShadow: "0 1px 3px rgba(0,0,0,0.03)"
            }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "8px" }}>
                <span style={{ fontSize: "12.5px", fontWeight: 600, color: "#64748B" }}>Key Rotation Pool</span>
                <Key size={16} color="#059669" />
              </div>
              <div style={{ fontSize: "24px", fontWeight: 800, color: "#0F172A" }}>
                {aiStats.active_keys_count} / {aiStats.total_keys_count}
              </div>
              <div style={{ fontSize: "11.5px", color: "#059669", marginTop: "4px" }}>
                Active rotating API keys
              </div>
            </div>
          </div>

          {/* 2-Column Section: Usage by Feature & Top Users */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 340px), 1fr))", gap: "24px" }}>
            
            {/* Usage by Feature */}
            <div style={{
              backgroundColor: "#FFFFFF", border: "1px solid #E2E8F0", borderRadius: "14px", padding: "24px",
              boxShadow: "0 1px 3px rgba(0,0,0,0.04)"
            }}>
              <h2 style={{ fontSize: "16px", fontWeight: 700, margin: "0 0 4px 0", color: "#0F172A" }}>
                Tokens by Platform Feature
              </h2>
              <p style={{ fontSize: "12px", color: "#64748B", margin: "0 0 18px 0" }}>
                Distribution of prompt and completion tokens across features
              </p>

              {aiStats.feature_breakdown.length === 0 ? (
                <div style={{ color: "#94A3B8", fontSize: "13px", textAlign: "center", padding: "30px 0" }}>
                  No AI calls recorded yet. Upload a CV or score a resume to see usage.
                </div>
              ) : (
                <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
                  {aiStats.feature_breakdown.map((f) => {
                    const maxTokens = Math.max(...aiStats.feature_breakdown.map(i => i.total_tokens), 1);
                    const pct = Math.round((f.total_tokens / maxTokens) * 100);
                    return (
                      <div key={f.feature}>
                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: "12.5px", marginBottom: "4px" }}>
                          <span style={{ fontWeight: 600, color: "#1E293B" }}>{f.feature_name}</span>
                          <span style={{ fontWeight: 700, color: "#7C3AED", fontSize: "12px" }}>
                            {f.total_tokens.toLocaleString()} tokens ({f.total_calls} calls)
                          </span>
                        </div>
                        <div style={{ height: "7px", backgroundColor: "#F1F5F9", borderRadius: "4px", overflow: "hidden" }}>
                          <div style={{
                            height: "100%", width: `${pct}%`,
                            background: "linear-gradient(90deg, #7C3AED 0%, #2563EB 100%)",
                            borderRadius: "4px", transition: "width 0.4s ease"
                          }} />
                        </div>
                        <div style={{ display: "flex", justifyContent: "space-between", fontSize: "11px", color: "#94A3B8", marginTop: "3px" }}>
                          <span>In: {f.input_tokens.toLocaleString()} · Out: {f.output_tokens.toLocaleString()}</span>
                          <span>Avg latency: {f.avg_response_time_ms} ms</span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

            {/* Top Users by Token Consumption */}
            <div style={{
              backgroundColor: "#FFFFFF", border: "1px solid #E2E8F0", borderRadius: "14px", padding: "24px",
              boxShadow: "0 1px 3px rgba(0,0,0,0.04)"
            }}>
              <h2 style={{ fontSize: "16px", fontWeight: 700, margin: "0 0 4px 0", color: "#0F172A" }}>
                Top Candidates by Token Usage
              </h2>
              <p style={{ fontSize: "12px", color: "#64748B", margin: "0 0 18px 0" }}>
                Individual user consumption breakdown
              </p>

              {aiStats.top_users.length === 0 ? (
                <div style={{ color: "#94A3B8", fontSize: "13px", textAlign: "center", padding: "30px 0" }}>
                  No user activity recorded yet.
                </div>
              ) : (
                <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                  {aiStats.top_users.map((u, idx) => (
                    <div
                      key={u.user_id}
                      onClick={() => u.user_id !== "anonymous" && router.push(`/admin/users/${u.user_id}`)}
                      style={{
                        display: "flex", alignItems: "center", justifyContent: "space-between",
                        padding: "8px 12px", borderRadius: "8px", backgroundColor: "#F8FAFC",
                        border: "1px solid #E2E8F0", cursor: u.user_id !== "anonymous" ? "pointer" : "default"
                      }}
                    >
                      <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                        <span style={{ fontSize: "12px", fontWeight: 700, color: "#94A3B8", width: "16px" }}>
                          #{idx + 1}
                        </span>
                        <div>
                          <div style={{ fontSize: "13px", fontWeight: 600, color: "#0F172A" }}>{u.full_name}</div>
                          <div style={{ fontSize: "11px", color: "#64748B" }}>{u.email}</div>
                        </div>
                      </div>
                      <div style={{ textAlign: "right" }}>
                        <div style={{ fontSize: "13px", fontWeight: 700, color: "#2563EB" }}>
                          {u.total_tokens.toLocaleString()} tokens
                        </div>
                        <div style={{ fontSize: "11px", color: "#64748B" }}>
                          {u.total_calls} calls
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Recent Live API Execution Logs Table */}
          <div style={{
            backgroundColor: "#FFFFFF", border: "1px solid #E2E8F0", borderRadius: "14px", padding: "24px",
            boxShadow: "0 1px 3px rgba(0,0,0,0.04)"
          }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "16px", flexWrap: "wrap", gap: "12px" }}>
              <div>
                <h2 style={{ fontSize: "16px", fontWeight: 700, margin: "0 0 2px 0", color: "#0F172A", display: "flex", alignItems: "center", gap: "8px" }}>
                  <Terminal size={18} color="#2563EB" />
                  <span>Real-Time AI API Call Logs</span>
                </h2>
                <p style={{ fontSize: "12px", color: "#64748B", margin: 0 }}>
                  Detailed trace of prompt & completion tokens per request
                </p>
              </div>

              {/* Filter Pills */}
              <div style={{ display: "flex", gap: "6px" }}>
                {["all", "cv", "ats", "interview", "improve", "errors"].map((f) => (
                  <button
                    key={f}
                    onClick={() => setLogFilter(f)}
                    style={{
                      padding: "4px 10px",
                      fontSize: "11.5px",
                      fontWeight: 600,
                      borderRadius: "6px",
                      border: "none",
                      backgroundColor: logFilter === f ? "#2563EB" : "#F1F5F9",
                      color: logFilter === f ? "#FFFFFF" : "#64748B",
                      cursor: "pointer",
                      textTransform: "capitalize",
                    }}
                  >
                    {f}
                  </button>
                ))}
              </div>
            </div>

            {filteredLogs.length === 0 ? (
              <div style={{ color: "#94A3B8", fontSize: "13px", textAlign: "center", padding: "40px 0" }}>
                No API logs match the selected filter.
              </div>
            ) : (
              <div style={{ overflowX: "auto" }}>
                <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
                  <thead>
                    <tr style={{ borderBottom: "2px solid #E2E8F0", textAlign: "left", color: "#64748B" }}>
                      <th style={{ padding: "8px 12px", fontWeight: 600 }}>Timestamp</th>
                      <th style={{ padding: "8px 12px", fontWeight: 600 }}>Candidate</th>
                      <th style={{ padding: "8px 12px", fontWeight: 600 }}>Feature</th>
                      <th style={{ padding: "8px 12px", fontWeight: 600 }}>Model</th>
                      <th style={{ padding: "8px 12px", fontWeight: 600 }}>Tokens (In / Out / Total)</th>
                      <th style={{ padding: "8px 12px", fontWeight: 600 }}>Latency</th>
                      <th style={{ padding: "8px 12px", fontWeight: 600 }}>Key Used</th>
                      <th style={{ padding: "8px 12px", fontWeight: 600 }}>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredLogs.map((log) => {
                      const dateStr = new Date(log.created_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" });
                      return (
                        <tr key={log.id} style={{ borderBottom: "1px solid #F1F5F9" }}>
                          <td style={{ padding: "10px 12px", color: "#64748B", whiteSpace: "nowrap" }}>{dateStr}</td>
                          <td style={{ padding: "10px 12px" }}>
                            <div style={{ fontWeight: 600, color: "#0F172A" }}>{log.user_name}</div>
                            <div style={{ fontSize: "11px", color: "#94A3B8" }}>{log.user_email}</div>
                          </td>
                          <td style={{ padding: "10px 12px" }}>
                            <span style={{
                              fontSize: "11px", fontWeight: 600, padding: "2px 8px", borderRadius: "10px",
                              backgroundColor: "#F3E8FF", color: "#7C3AED"
                            }}>
                              {log.feature}
                            </span>
                          </td>
                          <td style={{ padding: "10px 12px", color: "#475569", fontFamily: "monospace", fontSize: "11.5px" }}>
                            {log.model.split("/").pop() || log.model}
                          </td>
                          <td style={{ padding: "10px 12px", fontWeight: 600 }}>
                            <span style={{ color: "#2563EB" }}>{log.input_tokens}</span>
                            <span style={{ color: "#94A3B8" }}> / </span>
                            <span style={{ color: "#16A34A" }}>{log.output_tokens}</span>
                            <span style={{ color: "#94A3B8" }}> = </span>
                            <span style={{ color: "#0F172A", fontWeight: 700 }}>{log.total_tokens}</span>
                          </td>
                          <td style={{ padding: "10px 12px", color: "#64748B" }}>
                            {log.response_time_ms} ms
                          </td>
                          <td style={{ padding: "10px 12px", color: "#64748B", fontFamily: "monospace", fontSize: "11px" }}>
                            {log.api_key_hint || "default"}
                          </td>
                          <td style={{ padding: "10px 12px" }}>
                            <span style={{
                              fontSize: "11px", fontWeight: 700, padding: "2px 8px", borderRadius: "10px",
                              backgroundColor: log.status === "success" ? "#DCFCE7" : "#FEE2E2",
                              color: log.status === "success" ? "#15803D" : "#DC2626",
                            }}>
                              {log.status.toUpperCase()}
                            </span>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

